sequenceDiagram
  actor user as user
  participant browser as browser
  participant server as server

  Note over user: Write a new note "Hi"
  user ->> browser: click on "Save" button
  
  browser ->> server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
  Note right of browser: Browser submit payload note=Hi <br> from HTML form<br>with method POST
  server -->> browser: 302 Found - URL Redirect
  Note left of server: Server request to Browser <br/>to perform a GET
  
  browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/notes
  server -->> browser: 200 OK - The HTML document
  
  browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
  server -->> browser: 200 OK - The CSS file
  
  browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
  server -->> browser: 200 OK - The JavaScript file
  Note right of browser: The browser executes JS code <br>that requets JSON data from Server
  browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
  server -->> browser: [{ "content": "Hi", "date": "2025-08-13T06:38:59.209Z"},...]
  Note right of browser: 200 OK - Ready State 4 <br>The browser executes <br>the function that renders the notes
  browser ->> user: User can see the full list of notes